---
- name: yum |  Setup PostgreSQL repository for {{ ansible_distribution }}
  become: yes
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    state: installed
  when: ansible_distribution == "CentOS"
  tags: [db, postgresql]

- name: yum | Setup Citus repository for {{ ansible_distribution }}
  become: yes
  shell: curl https://install.citusdata.com/community/rpm.sh | sudo bash
  tags: [db, postgresql]

- name: yum | Install PostgreSQL and Citus
  become: yes
  become_method: sudo
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql96-server
    - postgresql96-contrib
    - postgresql96-devel
    - citus70_96
  register: install_postgresql
  tags: [db, postgresql]

- name: yum | Initialize PostgreSQL
  become: yes
  become_method: sudo
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: install_postgresql.changed
  tags: [db, postgresql]

- name: yum | MD5-encrypted password for PostgreSQL 1
  become: yes
  become_method: sudo
  replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: ^(host.*all.*all.*127.0.0.1\/32.*)ident$
    replace: \1md5
  tags: [db, postgresql]

- name: yum | MD5-encrypted password for PostgreSQL 2
  become: yes
  become_method: sudo
  replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: ^(host.*all.*all.*::1\/128.*)ident$
    replace: \1md5
  tags: [db, postgresql]

- name: yum | Start and Enable PostgreSQL
  become: yes
  become_method: sudo
  service:
    name: postgresql
    state: started
    enabled: yes
  tags: [db, postgresql]
